[2025-04-06 11:53:50,611] [line:25] [root] [INFO] - divide by 0
[2025-04-06 11:53:50,612] [line:26] [root] [ERROR] - An exception occurred
Traceback (most recent call last):
  File "/Users/mona/Documents/mlproject/src/exception.py", line 23, in <module>
    a=1/0
ZeroDivisionError: division by zero
